syntax = "proto3";

package proto;

option go_package = "github.com/File-Sharer/hash-generator-service/internal/pb";

message HashReq {
  string baseString = 1;
}

message HashRes {
  bool ok = 1;
  string hash = 2;
}

message NewUIDReq {
  string userLogin = 1;
}

message NewUIDRes {
  bool ok = 1;
  string uid = 2;
}

message NewJWTReq {
  string secret = 1;
  string userId = 2;
  string role = 3;
}

message NewJWTRes {
  bool ok = 1;
  string token = 2;
}

message DecodeJWTReq {
  string secret = 1;
  string jwt = 2;
}

message DecodeJWTRes {
  bool ok = 1;
  string userId = 2;
  string role = 3;
}

service Hasher {
  rpc Hash(HashReq) returns (HashRes) {}
  rpc NewUID(NewUIDReq) returns (NewUIDRes) {}
  rpc NewJWT(NewJWTReq) returns (NewJWTRes) {}
  rpc DecodeJWT(DecodeJWTReq) returns (DecodeJWTRes) {}
}
