// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: internal/proto/hash-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseString string `protobuf:"bytes,1,opt,name=baseString,proto3" json:"baseString,omitempty"`
}

func (x *HashReq) Reset() {
	*x = HashReq{}
	mi := &file_internal_proto_hash_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashReq) ProtoMessage() {}

func (x *HashReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hash_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashReq.ProtoReflect.Descriptor instead.
func (*HashReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_hash_service_proto_rawDescGZIP(), []int{0}
}

func (x *HashReq) GetBaseString() string {
	if x != nil {
		return x.BaseString
	}
	return ""
}

type HashRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *HashRes) Reset() {
	*x = HashRes{}
	mi := &file_internal_proto_hash_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRes) ProtoMessage() {}

func (x *HashRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hash_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRes.ProtoReflect.Descriptor instead.
func (*HashRes) Descriptor() ([]byte, []int) {
	return file_internal_proto_hash_service_proto_rawDescGZIP(), []int{1}
}

func (x *HashRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HashRes) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type NewUIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserLogin string `protobuf:"bytes,1,opt,name=userLogin,proto3" json:"userLogin,omitempty"`
}

func (x *NewUIDReq) Reset() {
	*x = NewUIDReq{}
	mi := &file_internal_proto_hash_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUIDReq) ProtoMessage() {}

func (x *NewUIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hash_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUIDReq.ProtoReflect.Descriptor instead.
func (*NewUIDReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_hash_service_proto_rawDescGZIP(), []int{2}
}

func (x *NewUIDReq) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

type NewUIDRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *NewUIDRes) Reset() {
	*x = NewUIDRes{}
	mi := &file_internal_proto_hash_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUIDRes) ProtoMessage() {}

func (x *NewUIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hash_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUIDRes.ProtoReflect.Descriptor instead.
func (*NewUIDRes) Descriptor() ([]byte, []int) {
	return file_internal_proto_hash_service_proto_rawDescGZIP(), []int{3}
}

func (x *NewUIDRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NewUIDRes) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type NewJWTReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Role   string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *NewJWTReq) Reset() {
	*x = NewJWTReq{}
	mi := &file_internal_proto_hash_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewJWTReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewJWTReq) ProtoMessage() {}

func (x *NewJWTReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hash_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewJWTReq.ProtoReflect.Descriptor instead.
func (*NewJWTReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_hash_service_proto_rawDescGZIP(), []int{4}
}

func (x *NewJWTReq) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *NewJWTReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NewJWTReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type NewJWTRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *NewJWTRes) Reset() {
	*x = NewJWTRes{}
	mi := &file_internal_proto_hash_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewJWTRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewJWTRes) ProtoMessage() {}

func (x *NewJWTRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hash_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewJWTRes.ProtoReflect.Descriptor instead.
func (*NewJWTRes) Descriptor() ([]byte, []int) {
	return file_internal_proto_hash_service_proto_rawDescGZIP(), []int{5}
}

func (x *NewJWTRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NewJWTRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DecodeJWTReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Jwt    string `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *DecodeJWTReq) Reset() {
	*x = DecodeJWTReq{}
	mi := &file_internal_proto_hash_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeJWTReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeJWTReq) ProtoMessage() {}

func (x *DecodeJWTReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hash_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeJWTReq.ProtoReflect.Descriptor instead.
func (*DecodeJWTReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_hash_service_proto_rawDescGZIP(), []int{6}
}

func (x *DecodeJWTReq) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *DecodeJWTReq) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type DecodeJWTRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Role   string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *DecodeJWTRes) Reset() {
	*x = DecodeJWTRes{}
	mi := &file_internal_proto_hash_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeJWTRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeJWTRes) ProtoMessage() {}

func (x *DecodeJWTRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hash_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeJWTRes.ProtoReflect.Descriptor instead.
func (*DecodeJWTRes) Descriptor() ([]byte, []int) {
	return file_internal_proto_hash_service_proto_rawDescGZIP(), []int{7}
}

func (x *DecodeJWTRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DecodeJWTRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DecodeJWTRes) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_internal_proto_hash_service_proto protoreflect.FileDescriptor

var file_internal_proto_hash_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x61, 0x73, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x07, 0x48, 0x61,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x2d, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x22, 0x29, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x55, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22,
	0x2d, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x4f,
	0x0a, 0x09, 0x4e, 0x65, 0x77, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22,
	0x31, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x38, 0x0a, 0x0c, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x4a, 0x57, 0x54, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x77,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x22, 0x4a, 0x0a, 0x0c,
	0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x32, 0xcb, 0x01, 0x0a, 0x06, 0x48, 0x61, 0x73,
	0x68, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2e, 0x0a,
	0x06, 0x4e, 0x65, 0x77, 0x55, 0x49, 0x44, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x65, 0x77, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2e, 0x0a,
	0x06, 0x4e, 0x65, 0x77, 0x4a, 0x57, 0x54, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x65, 0x77, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x37, 0x0a,
	0x09, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x4a, 0x57, 0x54, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x4a, 0x57,
	0x54, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x69, 0x6c, 0x65, 0x2d, 0x53, 0x68, 0x61, 0x72, 0x65, 0x72,
	0x2f, 0x68, 0x61, 0x73, 0x68, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_hash_service_proto_rawDescOnce sync.Once
	file_internal_proto_hash_service_proto_rawDescData = file_internal_proto_hash_service_proto_rawDesc
)

func file_internal_proto_hash_service_proto_rawDescGZIP() []byte {
	file_internal_proto_hash_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_hash_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_hash_service_proto_rawDescData)
	})
	return file_internal_proto_hash_service_proto_rawDescData
}

var file_internal_proto_hash_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_hash_service_proto_goTypes = []any{
	(*HashReq)(nil),      // 0: proto.HashReq
	(*HashRes)(nil),      // 1: proto.HashRes
	(*NewUIDReq)(nil),    // 2: proto.NewUIDReq
	(*NewUIDRes)(nil),    // 3: proto.NewUIDRes
	(*NewJWTReq)(nil),    // 4: proto.NewJWTReq
	(*NewJWTRes)(nil),    // 5: proto.NewJWTRes
	(*DecodeJWTReq)(nil), // 6: proto.DecodeJWTReq
	(*DecodeJWTRes)(nil), // 7: proto.DecodeJWTRes
}
var file_internal_proto_hash_service_proto_depIdxs = []int32{
	0, // 0: proto.Hasher.Hash:input_type -> proto.HashReq
	2, // 1: proto.Hasher.NewUID:input_type -> proto.NewUIDReq
	4, // 2: proto.Hasher.NewJWT:input_type -> proto.NewJWTReq
	6, // 3: proto.Hasher.DecodeJWT:input_type -> proto.DecodeJWTReq
	1, // 4: proto.Hasher.Hash:output_type -> proto.HashRes
	3, // 5: proto.Hasher.NewUID:output_type -> proto.NewUIDRes
	5, // 6: proto.Hasher.NewJWT:output_type -> proto.NewJWTRes
	7, // 7: proto.Hasher.DecodeJWT:output_type -> proto.DecodeJWTRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_hash_service_proto_init() }
func file_internal_proto_hash_service_proto_init() {
	if File_internal_proto_hash_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_hash_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_hash_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_hash_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_hash_service_proto_msgTypes,
	}.Build()
	File_internal_proto_hash_service_proto = out.File
	file_internal_proto_hash_service_proto_rawDesc = nil
	file_internal_proto_hash_service_proto_goTypes = nil
	file_internal_proto_hash_service_proto_depIdxs = nil
}
