// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: internal/proto/hash-service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hasher_Hash_FullMethodName            = "/proto.Hasher/Hash"
	Hasher_NewUID_FullMethodName          = "/proto.Hasher/NewUID"
	Hasher_NewJWT_FullMethodName          = "/proto.Hasher/NewJWT"
	Hasher_DecodeJWT_FullMethodName       = "/proto.Hasher/DecodeJWT"
	Hasher_GenerateJWTPair_FullMethodName = "/proto.Hasher/GenerateJWTPair"
)

// HasherClient is the client API for Hasher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HasherClient interface {
	Hash(ctx context.Context, in *HashReq, opts ...grpc.CallOption) (*HashRes, error)
	NewUID(ctx context.Context, in *NewUIDReq, opts ...grpc.CallOption) (*NewUIDRes, error)
	NewJWT(ctx context.Context, in *NewJWTReq, opts ...grpc.CallOption) (*NewJWTRes, error)
	DecodeJWT(ctx context.Context, in *DecodeJWTReq, opts ...grpc.CallOption) (*DecodeJWTRes, error)
	GenerateJWTPair(ctx context.Context, in *GenerateJWTPairReq, opts ...grpc.CallOption) (*GenerateJWTPairRes, error)
}

type hasherClient struct {
	cc grpc.ClientConnInterface
}

func NewHasherClient(cc grpc.ClientConnInterface) HasherClient {
	return &hasherClient{cc}
}

func (c *hasherClient) Hash(ctx context.Context, in *HashReq, opts ...grpc.CallOption) (*HashRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashRes)
	err := c.cc.Invoke(ctx, Hasher_Hash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherClient) NewUID(ctx context.Context, in *NewUIDReq, opts ...grpc.CallOption) (*NewUIDRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewUIDRes)
	err := c.cc.Invoke(ctx, Hasher_NewUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherClient) NewJWT(ctx context.Context, in *NewJWTReq, opts ...grpc.CallOption) (*NewJWTRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewJWTRes)
	err := c.cc.Invoke(ctx, Hasher_NewJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherClient) DecodeJWT(ctx context.Context, in *DecodeJWTReq, opts ...grpc.CallOption) (*DecodeJWTRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeJWTRes)
	err := c.cc.Invoke(ctx, Hasher_DecodeJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherClient) GenerateJWTPair(ctx context.Context, in *GenerateJWTPairReq, opts ...grpc.CallOption) (*GenerateJWTPairRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateJWTPairRes)
	err := c.cc.Invoke(ctx, Hasher_GenerateJWTPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HasherServer is the server API for Hasher service.
// All implementations must embed UnimplementedHasherServer
// for forward compatibility.
type HasherServer interface {
	Hash(context.Context, *HashReq) (*HashRes, error)
	NewUID(context.Context, *NewUIDReq) (*NewUIDRes, error)
	NewJWT(context.Context, *NewJWTReq) (*NewJWTRes, error)
	DecodeJWT(context.Context, *DecodeJWTReq) (*DecodeJWTRes, error)
	GenerateJWTPair(context.Context, *GenerateJWTPairReq) (*GenerateJWTPairRes, error)
	mustEmbedUnimplementedHasherServer()
}

// UnimplementedHasherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHasherServer struct{}

func (UnimplementedHasherServer) Hash(context.Context, *HashReq) (*HashRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hash not implemented")
}
func (UnimplementedHasherServer) NewUID(context.Context, *NewUIDReq) (*NewUIDRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewUID not implemented")
}
func (UnimplementedHasherServer) NewJWT(context.Context, *NewJWTReq) (*NewJWTRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewJWT not implemented")
}
func (UnimplementedHasherServer) DecodeJWT(context.Context, *DecodeJWTReq) (*DecodeJWTRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeJWT not implemented")
}
func (UnimplementedHasherServer) GenerateJWTPair(context.Context, *GenerateJWTPairReq) (*GenerateJWTPairRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateJWTPair not implemented")
}
func (UnimplementedHasherServer) mustEmbedUnimplementedHasherServer() {}
func (UnimplementedHasherServer) testEmbeddedByValue()                {}

// UnsafeHasherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HasherServer will
// result in compilation errors.
type UnsafeHasherServer interface {
	mustEmbedUnimplementedHasherServer()
}

func RegisterHasherServer(s grpc.ServiceRegistrar, srv HasherServer) {
	// If the following call pancis, it indicates UnimplementedHasherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hasher_ServiceDesc, srv)
}

func _Hasher_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hasher_Hash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServer).Hash(ctx, req.(*HashReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hasher_NewUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServer).NewUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hasher_NewUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServer).NewUID(ctx, req.(*NewUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hasher_NewJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServer).NewJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hasher_NewJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServer).NewJWT(ctx, req.(*NewJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hasher_DecodeJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServer).DecodeJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hasher_DecodeJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServer).DecodeJWT(ctx, req.(*DecodeJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hasher_GenerateJWTPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateJWTPairReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServer).GenerateJWTPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hasher_GenerateJWTPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServer).GenerateJWTPair(ctx, req.(*GenerateJWTPairReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Hasher_ServiceDesc is the grpc.ServiceDesc for Hasher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hasher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hasher",
	HandlerType: (*HasherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hash",
			Handler:    _Hasher_Hash_Handler,
		},
		{
			MethodName: "NewUID",
			Handler:    _Hasher_NewUID_Handler,
		},
		{
			MethodName: "NewJWT",
			Handler:    _Hasher_NewJWT_Handler,
		},
		{
			MethodName: "DecodeJWT",
			Handler:    _Hasher_DecodeJWT_Handler,
		},
		{
			MethodName: "GenerateJWTPair",
			Handler:    _Hasher_GenerateJWTPair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/hash-service.proto",
}
